# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
- ldflags:
  - -X "github.com/javijuol/git-remind/app/cli.Name=git-remind"
    -X "github.com/javijuol/git-remind/app/cli.Description=Never forget to git commit and push"
    -X "github.com/javijuol/git-remind/app/cli.Version={{.Version}}"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: git-remind
  github:
    owner: suin
    name: homebrew-suin
  folder: Formula
  homepage: "https://github.com/javijuol/git-remind/"
  description: "Never forget to git commit and push."
  dependencies:
  - git
